### ISSUE TITLE
Remove shim from memory if GUI is detected

### ISSUE THREAD

**Issue by trajano** [71/scoop-better-shimexe#5]
First good work on #4 

![image](https://user-images.githubusercontent.com/110627/64492264-332f7980-d240-11e9-8a2e-82023a3cfb74.png)

In details it sounds like you just hid the process and I can tell that from procexp.  Can you just terminate the process?

**Comment by 71** [comment]
It's unfortunately the only way to do it. I tried various other hacks that didn't involve just hiding the window automatically but none worked.

An executable either acts:
- as a console app, in which case it **must** create a console window if opened via `Win+R` for instance, or
- as a Windows app, in which case it cannot interact with the console through `stdout`, `stderr` or `stdin`.

Since most scoop apps are command line utilities (at least in my case), the second solution wasn't doable. We could have two different `.exe`s, but that would require scoop to track whether a shim points to a command line app or a Windows app.
